[project]
name = "xnodes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy",
    "opencv-contrib-python-headless",
    "rclpy",
    "sensor-msgs",
    "std-msgs",
    "std-srvs",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
