[build-system]
requires = ["setuptools", "wheel", "ament-setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "xnodes"
version = "0.1.0"
description = "ROS2 nodes for cameras and AprilTags"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rclpy",
    "sensor_msgs",
    "geometry_msgs",
    "opencv-contrib-python",
    "numpy",
    "tyro",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"xnodes" = ["launch/*.launch.py"]

[project.entry-points."console_scripts"]
apriltag_node = "xnodes.apriltag:main"
