from __future__ import annotations


def build_legacy_robot_launch_source(
    *,
    input_mode,
    ctrl_mode,
    backend,
    robot_ip,
    service_ns,
):
    return [
        "from xnodes.components.robot import RobotBackend, RobotConfig, InputMode, ControlMode; ",
        "from xnodes.nodes.legacy.robot import run; ",
        "run(RobotConfig(ip='",
        robot_ip,
        "', input=InputMode('",
        input_mode,
        "'), ctrl=ControlMode('",
        ctrl_mode,
        "'), backend=RobotBackend('",
        backend,
        "'), service_ns='",
        service_ns,
        "'))",
    ]


def build_real_robot_launch_source(
    *,
    robot_ip,
    dof,
    input_mode,
    ctrl_mode,
    backend,
    use_gripper,
    hz,
    grip_hz,
    service_ns,
):
    return [
        "from xnodes.components.robot import ControlMode, InputMode, RobotConfig; ",
        "from xnodes.components.robot import RobotBackend; ",
        "from xnodes.nodes.legacy.robot import run; ",
        "run(RobotConfig(",
        "ip='",
        robot_ip,
        "', ",
        "dof=",
        dof,
        ", ",
        "input=InputMode('",
        input_mode,
        "'), ",
        "ctrl=ControlMode('",
        ctrl_mode,
        "'), ",
        "backend=RobotBackend('",
        backend,
        "'), ",
        "use_gripper=",
        use_gripper,
        ", ",
        "hz=",
        hz,
        ", ",
        "grip_hz=",
        grip_hz,
        ", ",
        "service_ns='",
        service_ns,
        "'",
        "))",
    ]
