model:
  ros__parameters:
    host: localhost
    port: 8081
    rep: ABS
    task: none
    ensemble: false
    req_hz: 1.1
    cmd_hz: 25.0
    resolution: 1
    joint_topic: /joint_states
    pose_topic: /xarm/robot_states
    gripper_topic: /xgym/gripper
    state_topic: /gello/state
    low_camera_topic: /cam/low/image_raw
    side_camera_topic: /cam/side/image_raw
    wrist_camera_topic: /camera/camera/color/image_raw # wrist
