#!/bin/python
from __future__ import annotations

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description() -> LaunchDescription:
    params_file = LaunchConfiguration("params_file")

    footpedal = Node(
        package="xnodes",
        executable="footpedal",
        output="screen",
        emulate_tty=True,
        parameters=[params_file],
    )

    return LaunchDescription(
        [
            DeclareLaunchArgument(
                "params_file",
                default_value=PathJoinSubstitution([FindPackageShare("xnodes"), "config", "pedal.yaml"]),
                description="Foot pedal ROS parameter file",
            ),
            footpedal,
        ]
    )
